### ISSUE TITLE
Bug Report | Codeblock not working inside admonition callouts

### ISSUE THREAD

**Issue by LeCheenaX** [mugiwara85/CodeblockCustomizer#118]
## Issue Description
When `ad-*` is excluded in the setting, the codeblock inside an admonition callout will be the original style:  
![image](https://github.com/user-attachments/assets/520b83a2-6ea4-450e-9446-bdf9bbd09605)

### Source MD
\````ad-warning
Avoid declaring multiple variables with comma separator:

\```cpp
int a = 5, b = 10, c = 15; // Avoid declaring multiple variables in one line
\```

This helps to improve code clarity and maintainability(adding comments about meaning of the variable).
\````

## More Info
- Plugin Version: 1.2.8
- Platform: Windows 10

**Comment by mugiwara85** [comment]
Yes, and that is correct. In your case, this is a nested code block. If you exclude the outer code block, the inner code block will be excluded as well. 
Admonitions are obsolate since a long time. I don't know why a lot of people still use it. Use call outs instead:

![image](https://github.com/user-attachments/assets/a15e1f5a-f592-4c5b-90a9-23fa70a64d86)

```
> [!warning]
> ```cpp file:test
> int a = 5, b = 10, c = 15; // Avoid declaring multiple variables in one line  
> ```
```

**Comment by LeCheenaX** [comment]
The cases where codeblocks inside a callout are rare that using obsidian original callout `[!warning]` is completely acceptable. 

I often use admonition as the obsidian-style callout are somehow buggy in content display.
