### ISSUE TITLE
Limitation in Reading View?

### ISSUE THREAD

**Issue by Kani3D** [mugiwara85/CodeblockCustomizer#20]
Thanks for your effort! I really like your plugin.

Is there a way to increase the number of "customized" codeblocks? 
Im using the Multicolumn plugin as well (https://github.com/ckRobinson/multi-column-markdown)

Editing mode (fine):
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/105086349/f25caaaf-9735-4f06-bfb0-c54f80c62ecf)

Reading mode (only 4 codeblocks are customized)
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/105086349/5742f96c-dd2c-49d4-962f-78703536a19d)

- Attachments: The note.

Thank you.
[Scratchbook.md](https://github.com/mugiwara85/CodeblockCustomizer/files/11617956/Scratchbook.md)

**Comment by Kani3D** [comment]
Solved it by reloading the plugin.

**Comment by mugiwara85** [comment]
There is no limit how many code blocks will render. I don't know this plugin, but this is how it looks on my machine:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/12a053b4-0a1e-44f0-89aa-e86aa16b0933)
Try changing to a different theme, or disabling custom CSS (if applied) to see if it changes.
Also note, that there is also a problem with problem with Multicolumn plugin. It renders the document endlessly. I disabled my plugin and I saw this:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/d51b90f8-3575-4d5e-b809-d48f0a655593)
Even if I did not scroll up and down in the document the number before:
`[Violation] Forced reflow while executing JavaScript took <N>ms`
and 
`[Violation] 'setInterval' handler took <N>ms`
kept increasing. Which is not good, since it causes extra load for Obsidian.

**Comment by mugiwara85** [comment]
> Solved it by reloading the plugin.

You were faster than me :D

**Comment by Kani3D** [comment]
Thanks for the very detailed reply tho. 
Especially the endless rendering is something i was not aware of.
Really appreciate it.

**Comment by mugiwara85** [comment]
Anytime :)
