### ISSUE TITLE
Open Theme Discussions

### ISSUE THREAD

**Issue by mayurankv** [mugiwara85/CodeblockCustomizer#34]
Could you open a  github dicussion for the purpose of adding default popular themes such as gruvbox and nord etc.

**Comment by mugiwara85** [comment]
To be honest I am not a fan of this idea. I don't want that anyone comes and expects every possible theme. I definitely do not want to continously adding new themes. The plugins goal is to add customizeability. The user can create their own theme, that's why this option is there. Just because someone has an idea or would like a feature, it does not mean that it also would make sense for others. As I said, I am open for improvement, but the option has to make sense. The goal is not to make everything someone says. I also wrote in the Readme that if someone has a good theme I am willing to implement it. But there must be a limit what to do and what not to do. If I open a discussion everyone will come with their own favorite theme, which will result that I have to add 30 or more themes.

**Comment by mayurankv** [comment]
That's fine by me. Though I do hope to add just specifically the nord, Dracula and gruvbox themes after refactoring if you're ok with that?

**Comment by mugiwara85** [comment]
Yes, sure, go ahead. As I said, I just don't want to a ton of themes, because everyone has a different favorite.
