### ISSUE TITLE
Can the code block support default folding or fixed display width?

### ISSUE THREAD

**Issue by ku-zhen** [mugiwara85/CodeblockCustomizer#4]
Hello，can the code block support default folding or fixed display width? Sometimes the sample code block is too long, can you set a default display height? Exceeded content is browsed by means of scroll wheel, etc. Thanks~

**Comment by mugiwara85** [comment]
Hi,
default folding is included since the first version. You just have to write `fold` in the first line of the code block (just like as you would do with the `hl` parameter). This will fold the code block every time you open the document. It is documented in the README as well. Is this what you mean?
What do you mean by fixed width/height?
