### ISSUE TITLE
Changing theme resets other settings

### ISSUE THREAD

**Issue by RunsOnRum** [mugiwara85/CodeblockCustomizer#67]
Toggling the theme will switch on/off other settings such as Line numbers, code button, pdf settings etc. Also, thank you for a beautiful plugin :-)

**Comment by mugiwara85** [comment]
Only, if you are using the default themes :) That's why I wrote [here](https://github.com/mugiwara85/CodeblockCustomizer#themes): 
"When you switch themes, all unsaved changes are lost. Therefore it is recommended to create your own theme (unless you are happy with the default settings and will never change the theme), and always save your changes. If you made a change, and did not save it, the theme will not include it!"

**Comment by RunsOnRum** [comment]
Ah that's what I get for not reading the documentation thoroughly. Thank you for your quick reply.

**Comment by mugiwara85** [comment]
sure, no problem :)
