### ISSUE TITLE
[Bug] bug in simi-fold

### ISSUE THREAD

**Issue by 7Codez** [mugiwara85/CodeblockCustomizer#73]
Why if one line it is not appear like simi-fold.

and Can you add an option to make it always collapsed instead of calling it every time?

**Comment by mugiwara85** [comment]
Which line is not semi-folded?
What do you mean by always collapsed? There is an option fold, which when you define, then the code block appears folded when you open a note. Is this what you mean?

**Comment by 7Codez** [comment]
Glitch occurs in different mode
Editing view
![Screenshot_20240211-145950_Gallery](https://github.com/mugiwara85/CodeblockCustomizer/assets/130913316/de3f9283-13df-4457-8f8c-47e6290aa5a4)

Live preview
![Screenshot_20240211-150012_Gallery](https://github.com/mugiwara85/CodeblockCustomizer/assets/130913316/bf30f129-2fbe-4b17-a2d2-9237008de257)

Reading view
![Screenshot_20240211-150022_Gallery](https://github.com/mugiwara85/CodeblockCustomizer/assets/130913316/3fa5c904-8545-4190-8449-8e6ce53db5e1)




*in setting I choced 2 line to appear.

**Comment by mugiwara85** [comment]
Did you read the README? It is clearly written:
"If your code block does have the minimum required line (count of visible lines + 4 for fading effect), then it will semi-fold."
You one-line code block will not semi-fold because it contains only one line. To make semi-fold work, you'll need a code block with at least that many lines you selected+4 lines. So if you chose 1 line, then it means, your code block must contain at least 5 lines.

**Comment by 7Codez** [comment]
Yes but In these screens, I chose 1 line. You can write this text in Obsidian from your own and your page will appear like the screens.

Copy this text:

```one-line
1 why?
```

```tow-line
1
2 if five line
3
4
5
```

*in setting I choced 1 line to appare.

**Comment by mugiwara85** [comment]
I am not sure I understand the problem. Currently there is a small difference between editing and reading mode, which is also documented in the README: "There is a slight difference between editing mode and reading mode. In editing mode the first line of the code block (where you define the language and the parameters) also counts, in reading mode not, since it doesn't exist. This will probably change in the next release so it is the same between editing and reading mode."
Is this what you mean?
Other than that, as I explained earlier, for semi-code to work, the code block needs to have (the selected lines(in your case 1) + 4 lines), so in your case at least 5 lines. If it has less then 5 lines, it will fold normally.
As I am not sure what problem you have, you might want to switch notes once, after you switched to reading view.
Otherwise, please describe the problem in much more detail.

**Comment by mugiwara85** [comment]
no more reply received
