### ISSUE TITLE
Highlight bugs

### ISSUE THREAD

**Issue by Kang-geophysics** [mugiwara85/CodeblockCustomizer#86]
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/56065588/f88ac04e-9748-42d1-a055-c7a4dc0d62fc)
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/56065588/67449bd4-6997-408a-8323-9b04c1af4d28)

Hi, I really love this plugin. 
Btw, I found a simple bug.

The highlight command seems to have order dependency.
As you can see in Figure 1, the highlight works well.
But, in Figure 2, the default command "hl" doesn't work. 

I found that the command "h" aligned after customized hl command doesn't work.

Thanks.

**Comment by mugiwara85** [comment]
Hi! 
Thanks!
Unfortunately, I can't reproduce this issue:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/16c1955e-babd-4a5b-a2a6-626fd5215903)

Is it possible that you have editor active line highlight or codeblock active line highlight enabled, and you clicked in the second line on the second screenshot? Active line highlight takes precedence over any highlight, because otherwise you wouldn't see in which line the cursor is in. But other than that, it should not matter in which order you specified the highlight parameters (as long as they are not overlapping).

**Comment by Kang-geophysics** [comment]
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/56065588/7e6e6758-8106-4bf1-a8a7-453f062c7e7e)
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/56065588/1e3191a7-0dc0-4c8d-8ba1-e42c86155b76)

It's strange; I didn't click on the second line. I attempted it once more, yet it still fails to work. By the way, it's not important. Thank you for your effort. There seems to be a problem, but I'm not sure what it is yet. If I discover anything else, I'll inform you.

**Comment by mugiwara85** [comment]
Interesting. Well if it's a bug, I will gladly fix it, I just have to reproduce it :)
What Obsidian Theme are you using? Also could you send me your data.json file? It can be found in your Vaultfolder\.obsidian\plugins\codeblock-customizer\

**Comment by Kang-geophysics** [comment]
I am using "Minimal Theme"

This is my data.json file.
[data.json](https://github.com/mugiwara85/CodeblockCustomizer/files/15429998/data.json)

Thanks

**Comment by mugiwara85** [comment]
And you are right! Now I can reproduce it. It really doesn't work. Very interesting. I check it, and get back to you.

**Comment by mugiwara85** [comment]
I rewrote the parameter parsing part, and it should work now, but please test it. Maybe you find something else :) This was a very good find!
You can just take the main.js and overwrite yours with it (until it is released)

**Comment by Kang-geophysics** [comment]
Thank you for your efforts! I truly appreciate the improvements. It functions well in live view mode, as you can observe.
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/56065588/7bdad4b5-6604-48b4-9eb1-ae7672c20d68)
 
 By the way, I found related error.
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/56065588/ee93f30a-3123-4066-b497-2945bccbf0a3)
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/56065588/d4003e2c-efdc-4624-abfb-68e7ee09c4ba)
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/56065588/109b70fe-d509-4aec-a2a4-29c7deeead06)

I created three code blocks. In the first block, lines 3 and 4 are highlighted with "hl" and lines 1 and 6 with "ghl". In the second block, line 1 is highlighted with "ghl", lines 2 and 6 with "yhl", and lines 3 and 4 with "hl". In the third block, lines 3 and 4 are highlighted with "hl" and line 5 with "yhl". However, when I switch to reading view, the "ghl" and "yhl" highlights disappear in the second block.

Thank you!

**Comment by mugiwara85** [comment]
Hi!
This probably a refresh problem, because it is working for me.

Source mode:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/ee410986-21d1-41df-9e92-c5f3b041e2c3)

Reading mode:
![image](https://github.com/mugiwara85/CodeblockCustomizer/assets/65603765/fcec5684-b5b3-4cb4-adb6-94705da4cf09)

One thing I can think when something like this happens is when you are editing the document, then switch to reading mode, then back to edit mode, make some changes (like adding the last highlighting to the second code block which didn't work), and then back to reading mode again. 
Could you please test it, if this is the case? If yes, then just switch to another document in reading mode, and switch back to this one. That should solve it.

**Comment by Kang-geophysics** [comment]
Yes, that's correct. The issue arose after making a few changes to the code block. However, when I switch to a different note, the problem resolves. I had anticipated that the changes would also affect the reading mode directly.

**Comment by mugiwara85** [comment]
Well they do....sort of. Not all the changes have immediate effect. It is complicated. I am working on it.

**Comment by Kang-geophysics** [comment]
I really appreciate your effort. Thank you very much.

**Comment by mugiwara85** [comment]
Finally released. Available in version 1.2.7.
